### ISSUE TITLE
建议把父容器改成背景透明

### ISSUE THREAD

**Issue by kamike** [wilin52/popup_window#1]
自定义弹框，想设置背景半透明window:Container(color:Color(0x11000000))，这样设置无效，修改后就可以了
Material(
                    type: type,
                    elevation: elevation,
                    child: child,
                    color: Colors.transparent,
                  )
![image](https://user-images.githubusercontent.com/3920019/84479127-ff98e880-acc4-11ea-8b21-76279b6a093d.png)

**Comment by wilin52** [comment]
> 自定义弹框，想设置背景半透明window:Container(color:Color(0x11000000))，这样设置无效，修改后就可以了
> Material(
> type: type,
> elevation: elevation,
> child: child,
> color: Colors.transparent,
> )
> ![image](https://user-images.githubusercontent.com/3920019/84479127-ff98e880-acc4-11ea-8b21-76279b6a093d.png)

哈喽，可以的。你也可以在外面设置主题：
![image](https://user-images.githubusercontent.com/9528566/84560320-552cce00-ad75-11ea-8d69-752d3dc6e212.png)

**Comment by wilin52** [comment]
> 自定义弹框，想设置背景半透明window:Container(color:Color(0x11000000))，这样设置无效，修改后就可以了
> Material(
> type: type,
> elevation: elevation,
> child: child,
> color: Colors.transparent,
> )
> ![image](https://user-images.githubusercontent.com/3920019/84479127-ff98e880-acc4-11ea-8b21-76279b6a093d.png)

更新到最新，增加了builder 方法，可以自定义动画和背景
