### ISSUE TITLE
用不了

### ISSUE THREAD

**Issue by yyy000112** [wilin52/popup_window#2]
这个没法用啊，提示PopupWindowButton不是一个方法

**Comment by wilin52** [comment]
@yyy000112 你好，根据readme get started 配置后执行flutter pub get下载就好了

**Comment by fanzhouyou** [comment]
> @yyy000112 你好，根据readme get started 配置后执行flutter pub get下载就好了

depends on popup_window ^1.0.0+4 which doesn't match any versions, version solving failed

**Comment by wilin52** [comment]
@fanzhouyou 被墙了吗？或者配置flutter_pub_hosted试试，中文网站有介绍

**Comment by wilin52** [comment]
@fanzhouyou 或者使用1.0.3

**Comment by wilin52** [comment]
> > @yyy000112 你好，根据readme get started 配置后执行flutter pub get下载就好了
> 
> depends on popup_window ^1.0.0+4 which doesn't match any versions, version solving failed

可能是因为镜像的原因，新版本需要过几天才能同步。

**Comment by wilin52** [comment]
没有回复，暂时关闭
