### ISSUE TITLE
在你的 popupwindow 下 添加 listview.builder 为啥显示字体 红色和 横线

### ISSUE THREAD

**Issue by haohao9102** [wilin52/popup_window#5]
![image](https://user-images.githubusercontent.com/24785148/113851722-60eaf480-97ce-11eb-903f-db72e85e5825.png)

**Comment by haohao9102** [comment]
PopupWindowButton(
                offset: Offset(0, 150),
                buttonBuilder: (context) {
                  return Container(
                    padding: EdgeInsets.fromLTRB(15, 2, 0, 2),
                    child: JTText('全部指令', style: TextStyle(fontSize: 14)),
                  );
                },
                windowBuilder: (BuildContext context,
                    Animation<double> animation,
                    Animation<double> secondaryAnimation) {
                  return FadeTransition(
                    opacity: animation,
                    child: SizeTransition(
                      sizeFactor: animation,
                      child: Container(
                        color: Colors.white,
                        child: ListView.builder(
                            itemCount: _statusStr.length,
                            shrinkWrap: true,
                            itemBuilder: (context, index) {
                              return GestureDetector(
                                onTap: (){
                                  Navigator.pop(context);
                                },
                                child:Container(
                                  padding: EdgeInsets.fromLTRB(15, 4,15, 4),
                                  child: Text(
                                    '${_statusStr[index]}',
                                    style: TextStyle(fontSize: 14,color: GlobalColors.color_000000),
                                  ),
                                ) ,
                              )
                                ;
                            }),
                      ),
                    ),
                  );
                },
              )

**Comment by wilin52** [comment]
需要在最外层套一个material  或者scaffold

**Comment by wilin52** [comment]
> PopupWindowButton(
> offset: Offset(0, 150),
> buttonBuilder: (context) {
> return Container(
> padding: EdgeInsets.fromLTRB(15, 2, 0, 2),
> child: JTText('全部指令', style: TextStyle(fontSize: 14)),
> );
> },
> windowBuilder: (BuildContext context,
> Animation animation,
> Animation secondaryAnimation) {
> return FadeTransition(
> opacity: animation,
> child: SizeTransition(
> sizeFactor: animation,
> child: Container(
> color: Colors.white,
> child: ListView.builder(
> itemCount: _statusStr.length,
> shrinkWrap: true,
> itemBuilder: (context, index) {
> return GestureDetector(
> onTap: (){
> Navigator.pop(context);
> },
> child:Container(
> padding: EdgeInsets.fromLTRB(15, 4,15, 4),
> child: Text(
> '${_statusStr[index]}',
> style: TextStyle(fontSize: 14,color: GlobalColors.color_000000),
> ),
> ) ,
> )
> ;
> }),
> ),
> ),
> );
> },
> )

需要在最外层套一个material 或者scaffold

**Comment by haohao9102** [comment]
最外层??  即 build return？？？？

**Comment by wilin52** [comment]
> 最外层?? 即 build return？？？？
原因在于你的页面不是一个material widget。详细看一下demo

**Comment by wilin52** [comment]
> 最外层?? 即 build return？？？？

最外层?? 即 build return？？？？
原因在于你的页面不是一个material widget。详细看一下demo

**Comment by wilin52** [comment]
@haohao9102 怎么样了？ 可以么？ 我先关掉issue了
